require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SiteSetupsController do

  # This should return the minimal set of attributes required to create a valid
  # SiteSetup. As you add validations to SiteSetup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "kickstarter" => "false" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SiteSetupsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all site_setups as @site_setups" do
      site_setup = SiteSetup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:site_setups).should eq([site_setup])
    end
  end

  describe "GET show" do
    it "assigns the requested site_setup as @site_setup" do
      site_setup = SiteSetup.create! valid_attributes
      get :show, {:id => site_setup.to_param}, valid_session
      assigns(:site_setup).should eq(site_setup)
    end
  end

  describe "GET new" do
    it "assigns a new site_setup as @site_setup" do
      get :new, {}, valid_session
      assigns(:site_setup).should be_a_new(SiteSetup)
    end
  end

  describe "GET edit" do
    it "assigns the requested site_setup as @site_setup" do
      site_setup = SiteSetup.create! valid_attributes
      get :edit, {:id => site_setup.to_param}, valid_session
      assigns(:site_setup).should eq(site_setup)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SiteSetup" do
        expect {
          post :create, {:site_setup => valid_attributes}, valid_session
        }.to change(SiteSetup, :count).by(1)
      end

      it "assigns a newly created site_setup as @site_setup" do
        post :create, {:site_setup => valid_attributes}, valid_session
        assigns(:site_setup).should be_a(SiteSetup)
        assigns(:site_setup).should be_persisted
      end

      it "redirects to the created site_setup" do
        post :create, {:site_setup => valid_attributes}, valid_session
        response.should redirect_to(SiteSetup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved site_setup as @site_setup" do
        # Trigger the behavior that occurs when invalid params are submitted
        SiteSetup.any_instance.stub(:save).and_return(false)
        post :create, {:site_setup => { "kickstarter" => "invalid value" }}, valid_session
        assigns(:site_setup).should be_a_new(SiteSetup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SiteSetup.any_instance.stub(:save).and_return(false)
        post :create, {:site_setup => { "kickstarter" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested site_setup" do
        site_setup = SiteSetup.create! valid_attributes
        # Assuming there are no other site_setups in the database, this
        # specifies that the SiteSetup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SiteSetup.any_instance.should_receive(:update_attributes).with({ "kickstarter" => "false" })
        put :update, {:id => site_setup.to_param, :site_setup => { "kickstarter" => "false" }}, valid_session
      end

      it "assigns the requested site_setup as @site_setup" do
        site_setup = SiteSetup.create! valid_attributes
        put :update, {:id => site_setup.to_param, :site_setup => valid_attributes}, valid_session
        assigns(:site_setup).should eq(site_setup)
      end

      it "redirects to the site_setup" do
        site_setup = SiteSetup.create! valid_attributes
        put :update, {:id => site_setup.to_param, :site_setup => valid_attributes}, valid_session
        response.should redirect_to(site_setup)
      end
    end

    describe "with invalid params" do
      it "assigns the site_setup as @site_setup" do
        site_setup = SiteSetup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SiteSetup.any_instance.stub(:save).and_return(false)
        put :update, {:id => site_setup.to_param, :site_setup => { "kickstarter" => "invalid value" }}, valid_session
        assigns(:site_setup).should eq(site_setup)
      end

      it "re-renders the 'edit' template" do
        site_setup = SiteSetup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SiteSetup.any_instance.stub(:save).and_return(false)
        put :update, {:id => site_setup.to_param, :site_setup => { "kickstarter" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested site_setup" do
      site_setup = SiteSetup.create! valid_attributes
      expect {
        delete :destroy, {:id => site_setup.to_param}, valid_session
      }.to change(SiteSetup, :count).by(-1)
    end

    it "redirects to the site_setups list" do
      site_setup = SiteSetup.create! valid_attributes
      delete :destroy, {:id => site_setup.to_param}, valid_session
      response.should redirect_to(site_setups_url)
    end
  end

end
